### ISSUE TITLE
Разобраться какую либу использовать для визуализации

### ISSUE THREAD

**Issue by light5551** [light5551/SummerPracticeVkFriends#3]
Возможно JavaFx или Java-Swing. Стоит разобраться какую стоит использовать в проекте. Сама задача состоит в том, чтобы создать [wiki](https://github.com/light5551/SummerPracticeVkFriends/wiki) страницу, где будет указаны ссылки на полезные ресурсы, а еще лучше участок кода с пояснениями и его результат с использованием выбранной либы.

**Comment by yawningstudent** [comment]
Инструкция [здесь](https://github.com/light5551/SummerPracticeVkFriends/wiki/Visualization)
